name: flutter_box_transform
description: "A new Flutter project."
version: 0.0.1
homepage: "https://github.com/4u1514g/flutter_box_transform.git"

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: any
  coverage: any
